"""Utilities for normalizing C++ code generated by language models."""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
from pathlib import Path


def _extract_code(raw_code: object) -> str:
    """Return source from a plain string or a Markdown code fence."""
    text = str(raw_code or "").strip()
    match = re.search(
        r"```(?:cpp|c\+\+|cc|c)?\s*(.*?)```", text, re.IGNORECASE | re.DOTALL
    )
    return match.group(1).strip() if match else text


def _strip_comments(source: str) -> str:
    """Remove C++ comments while preserving quoted literals and newlines."""
    output: list[str] = []
    index = 0
    state = "code"
    while index < len(source):
        current = source[index]
        following = source[index + 1] if index + 1 < len(source) else ""
        if state == "code":
            if current == '"':
                state = "double"
                output.append(current)
            elif current == "'":
                state = "single"
                output.append(current)
            elif current == "/" and following == "/":
                output.append(" ")
                index += 2
                while index < len(source) and source[index] not in "\r\n":
                    index += 1
                continue
            elif current == "/" and following == "*":
                output.append(" ")
                index += 2
                while index < len(source):
                    if source[index : index + 2] == "*/":
                        index += 2
                        break
                    if source[index] in "\r\n":
                        output.append(source[index])
                    index += 1
                continue
            else:
                output.append(current)
        else:
            output.append(current)
            if current == "\\" and following:
                output.append(following)
                index += 1
            elif (state == "double" and current == '"') or (
                state == "single" and current == "'"
            ):
                state = "code"
        index += 1
    return "".join(output)


def remove_comments(source: str, lang: str = "cpp") -> str:
    """Remove C++ comments; retain Ruby source unchanged for API compatibility."""
    if lang.lower() == "ruby":
        return remove_blank_lines(source)
    return remove_blank_lines(_strip_comments(source))


def remove_blank_lines(source: str) -> str:
    """Remove empty lines while retaining code order and indentation."""
    normalized = source.replace("\r\n", "\n").replace("\r", "\n")
    lines = [line.rstrip() for line in normalized.split("\n") if line.strip()]
    return "\n".join(lines).strip()


def format_cpp_code(source: str, clang_format_path: str | None = None) -> str:
    """Format C++ with clang-format when available, with a deterministic fallback."""
    source = _extract_code(source).replace("\r\n", "\n").replace("\r", "\n")
    executable = clang_format_path or shutil.which("clang-format")
    if executable:
        try:
            result = subprocess.run(
                [executable, "--assume-filename=snippet.cpp"],
                input=source,
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
                timeout=30,
                check=False,
            )
            if result.returncode == 0 and result.stdout.strip():
                return remove_blank_lines(result.stdout)
        except (OSError, subprocess.SubprocessError):
            pass
    lines = [line.rstrip() for line in source.splitlines()]
    fallback = re.sub(r"\n{3,}", "\n\n", "\n".join(lines))
    return fallback.strip()


def simple_sanitize_cpp(raw_code: object) -> str:
    """Run the lightweight C++ normalization pass."""
    source = _extract_code(raw_code)
    if not source or source == "pass":
        return "pass"
    return format_cpp_code(source)


def sanitize_and_strip_comments_cpp(raw_code: object) -> str:
    """Remove comments and format the resulting C++ source."""
    source = _extract_code(raw_code)
    if not source or source == "pass":
        return "pass"
    source = remove_comments(source)
    source = format_cpp_code(source)
    return remove_comments(source)


def repeated_sanitize_cpp(raw_code: object) -> str:
    """Compatibility alias for the stable comment-removing C++ pass."""
    return sanitize_and_strip_comments_cpp(raw_code)


def initialize_tokenizer(model_path: str):
    """Load an optional Hugging Face tokenizer only when token filtering is used."""
    try:
        from transformers import AutoTokenizer
    except ImportError as exc:
        raise RuntimeError(
            "Token-length filtering requires the optional transformers package."
        ) from exc
    return AutoTokenizer.from_pretrained(model_path)


def remove_long_code(source: str, tokenizer, max_length: int = 1024) -> str:
    """Return ``pass`` when a tokenizer reports a source longer than the limit."""
    source = source.strip()
    if not source or source == "pass" or tokenizer is None:
        return source or "pass"
    try:
        token_ids = tokenizer.encode(source, add_special_tokens=False)
    except TypeError:
        token_ids = tokenizer.encode(source)
    return "pass" if len(token_ids) > max_length else source


def knowledge_base_sanitize_cpp(
    raw_code: object,
    tokenizer=None,
    max_length: int = 1024,
    clang_format_path: str | None = None,
) -> str:
    """Prepare C++ source for knowledge-base indexing and optional token limits."""
    source = _extract_code(raw_code)
    if not source or source == "pass":
        return "pass"
    source = remove_comments(source)
    source = format_cpp_code(source, clang_format_path=clang_format_path)
    source = remove_comments(source)
    return remove_long_code(source, tokenizer, max_length)


def formatCppcode_function(raw_code: str) -> str:
    """Compatibility name for :func:`format_cpp_code`."""
    return format_cpp_code(raw_code)


def sanitize_Cpp_function(rawcode: object) -> str:
    """Compatibility name for the lightweight C++ sanitizer."""
    return simple_sanitize_cpp(rawcode)


def sanitize_and_strip_comments_Cpp_function(rawcode: object) -> str:
    """Compatibility name for comment-removing C++ sanitization."""
    return sanitize_and_strip_comments_cpp(rawcode)


def repeated_sanitize_Cpp_function(rawcode: object) -> str:
    """Compatibility name for repeated-generation C++ sanitization."""
    return repeated_sanitize_cpp(rawcode)


def knowledge_base_sanitize_Cpp_function(
    rawcode: object, tokenizer=None, max_length: int = 1024
) -> str:
    """Compatibility name for knowledge-base C++ sanitization."""
    return knowledge_base_sanitize_cpp(rawcode, tokenizer, max_length)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-path", type=Path, required=True, help="UTF-8 source file")
    parser.add_argument("--output-path", type=Path, help="Optional output file")
    parser.add_argument(
        "--mode",
        choices=("simple", "comments", "knowledge"),
        default="comments",
        help="Sanitization level",
    )
    parser.add_argument("--tokenizer-path", help="Optional tokenizer directory for knowledge mode")
    parser.add_argument("--max-length", type=int, default=1024, help="Maximum tokenizer length")
    parser.add_argument("--clang-format-path", help="Optional clang-format executable")
    return parser.parse_args()


def main() -> None:
    args = _parse_args()
    source = args.input_path.read_text(encoding="utf-8")
    if args.mode == "simple":
        result = simple_sanitize_cpp(source)
    elif args.mode == "knowledge":
        tokenizer = initialize_tokenizer(args.tokenizer_path) if args.tokenizer_path else None
        result = knowledge_base_sanitize_cpp(
            source,
            tokenizer=tokenizer,
            max_length=args.max_length,
            clang_format_path=args.clang_format_path,
        )
    else:
        result = sanitize_and_strip_comments_cpp(source)
    if args.output_path:
        args.output_path.write_text(result + "\n", encoding="utf-8")
    else:
        print(result)


if __name__ == "__main__":
    main()
