"""Utilities for normalizing Python code generated by language models.

The module exposes three levels of normalization used by the experiments:

``simple_sanitize_python``
    Removes execution guards and a few known runtime hazards while preserving
    comments and most of the original source structure.
``sanitize_and_strip_comments_python``
    Applies the simple pass and removes comments and docstrings.
``repeated_sanitize_python``
    Adds the conservative compatibility filters used for repeated-generation
    evaluation, such as removing process creation and dynamic execution.

All transformations are deterministic and use only the Python standard
library.  The compatibility wrappers at the bottom keep the public API used
by earlier experiment scripts.
"""

from __future__ import annotations

import argparse
import ast
import io
import re
import tokenize
from pathlib import Path
from typing import Callable


DEBUG = False


def _extract_code(raw_code: object) -> str:
    """Return source from a plain string or a Markdown code fence."""
    text = str(raw_code or "").strip()
    match = re.search(r"```(?:python|py)?\s*(.*?)```", text, re.IGNORECASE | re.DOTALL)
    return match.group(1).strip() if match else text


def remove_blank_lines(source: str) -> str:
    """Remove empty lines while retaining indentation and line order."""
    normalized = source.replace("\r\n", "\n").replace("\r", "\n")
    lines = [line.rstrip() for line in normalized.split("\n") if line.strip()]
    return "\n".join(lines).strip()


def _replace_matching_lines(
    source: str,
    predicate: Callable[[str], bool],
    replacement: str = "pass",
) -> str:
    lines: list[str] = []
    for line in source.splitlines():
        if predicate(line):
            indentation = line[: len(line) - len(line.lstrip())]
            lines.append(f"{indentation}{replacement}")
        else:
            lines.append(line)
    return "\n".join(lines)


def fix_ast_replacements(source: str) -> str:
    """Apply small repairs for recurring malformed generated Python patterns."""
    repaired = source.replace("print((", "print(tuple(")
    repaired = repaired.replace("sudo reboot", "")
    repaired = repaired.replace("shutdown -r", "")
    repaired = re.sub(r"\bshutdown\s+", "", repaired)
    return repaired.strip()


def _is_docstring_expression(node: ast.AST) -> bool:
    return isinstance(node, ast.Expr) and isinstance(
        getattr(node, "value", None), ast.Constant
    ) and isinstance(node.value.value, str)


def _remove_docstrings(node: ast.AST) -> None:
    """Remove module, class, and function docstrings in place."""
    body = getattr(node, "body", None)
    if isinstance(body, list) and body and _is_docstring_expression(body[0]):
        body.pop(0)
    for child in ast.iter_child_nodes(node):
        _remove_docstrings(child)


def normalize_ast(source: str, remove_docstrings: bool = False) -> str:
    """Parse and unparse Python source, or return the original on syntax errors."""
    try:
        tree = ast.parse(source.strip())
        if remove_docstrings:
            _remove_docstrings(tree)
        ast.fix_missing_locations(tree)
        return ast.unparse(tree).strip()
    except (SyntaxError, ValueError, TypeError):
        if DEBUG:
            print("Python AST normalization skipped because parsing failed.")
        return source.strip()


class CommentRemover(ast.NodeTransformer):
    """Compatibility transformer that removes standalone string expressions."""

    def visit_Expr(self, node: ast.Expr) -> ast.AST | None:
        if isinstance(getattr(node, "value", None), ast.Constant) and isinstance(
            node.value.value, str
        ):
            return None
        return self.generic_visit(node)


def _strip_python_comments(source: str) -> str:
    """Remove Python comment tokens without changing strings."""
    try:
        tokens = tokenize.generate_tokens(io.StringIO(source).readline)
        filtered = [token for token in tokens if token.type != tokenize.COMMENT]
        return tokenize.untokenize(filtered).strip()
    except (IndentationError, tokenize.TokenError):
        return source.strip()


def _strip_c_like_comments(source: str) -> str:
    """Remove C/C++ comments while preserving quoted literals and newlines."""
    output: list[str] = []
    index = 0
    state = "code"
    while index < len(source):
        current = source[index]
        following = source[index + 1] if index + 1 < len(source) else ""
        if state == "code":
            if current == '"':
                state = "double"
                output.append(current)
            elif current == "'":
                state = "single"
                output.append(current)
            elif current == "/" and following == "/":
                output.append(" ")
                index += 2
                while index < len(source) and source[index] not in "\r\n":
                    index += 1
                continue
            elif current == "/" and following == "*":
                output.append(" ")
                index += 2
                while index < len(source):
                    if source[index : index + 2] == "*/":
                        index += 2
                        break
                    if source[index] in "\r\n":
                        output.append(source[index])
                    index += 1
                continue
            else:
                output.append(current)
        else:
            output.append(current)
            if current == "\\" and following:
                output.append(following)
                index += 1
            elif (state == "double" and current == '"') or (
                state == "single" and current == "'"
            ):
                state = "code"
        index += 1
    return "".join(output)


def remove_comments_and_docstrings(source: str, lang: str = "python") -> str:
    """Remove comments and docstrings for Python, or comments for C-like code."""
    if lang.lower() in {"python", "py"}:
        normalized = normalize_ast(source, remove_docstrings=True)
        if normalized == source.strip():
            normalized = _strip_python_comments(source)
        return remove_blank_lines(normalized)
    if lang.lower() in {"ruby"}:
        return remove_blank_lines(source)
    return remove_blank_lines(_strip_c_like_comments(source))


def remove_recursion_limits(source: str) -> str:
    """Remove generated recursion and thread-stack limit changes."""
    return "\n".join(
        line
        for line in source.splitlines()
        if "setrecursionlimit(" not in line and "stack_size(" not in line
    )


def _is_main_guard(node: ast.If) -> bool:
    test = node.test
    return (
        isinstance(test, ast.Compare)
        and isinstance(test.left, ast.Name)
        and test.left.id == "__name__"
        and len(test.ops) == 1
        and isinstance(test.ops[0], ast.Eq)
        and len(test.comparators) == 1
        and isinstance(test.comparators[0], ast.Constant)
        and test.comparators[0].value == "__main__"
    )


def remove_main_guard(source: str) -> str:
    """Lift the body of a top-level ``if __name__ == '__main__'`` block."""
    try:
        tree = ast.parse(source.strip())
    except (SyntaxError, ValueError):
        return source.strip()
    new_body: list[ast.stmt] = []
    for node in tree.body:
        new_body.extend(node.body if isinstance(node, ast.If) and _is_main_guard(node) else [node])
    tree.body = new_body
    ast.fix_missing_locations(tree)
    return ast.unparse(tree).strip()


def replace_identity_operators(source: str) -> str:
    """Preserve the legacy normalization of textual identity comparisons."""
    return source.replace(" is not ", " != ").replace(" is ", " == ")


def apply_safe_io_replacements(source: str) -> str:
    """Replace common judge-specific stream operations with portable output."""
    repaired = source.replace("sys.stdin.buffer.read", "sys.stdin.read")
    repaired = repaired.replace("sys.stdin.buffer.readline", "sys.stdin.readline")
    repaired = re.sub(r"sys\.stdout\.write\((.*?)\)", r"print(\1, end='')", repaired)
    repaired = re.sub(r"sys\.stderr\.write\((.*?)\)", r"print(\1, end='')", repaired)
    repaired = re.sub(r"return\s+sys\.(?:stdout|stderr)\.flush\(\)", "return", repaired)
    return repaired


def replace_odd_words(source: str) -> str:
    """Remove generated I/O wrappers that interfere with standalone execution."""
    result: list[str] = []
    io_terms = (
        "IOWrapper(",
        "FastIO(",
        "StringIO(",
        "BytesIO(",
        "FastStdout(",
        "sys.stdout",
        "sys.stderr",
    )
    for line in source.splitlines():
        line = line.replace("from sys import stdout, ", "from sys import ")
        line = line.replace("from sys import stderr, ", "from sys import ")
        line = re.sub(r"from sys import (?:stdout|stderr)\s*$", "", line)
        line = re.sub(r"\bfile\s*=\s*sys\.stdout\s*,?", "", line)
        line = re.sub(r"\boutput\s*=\s*sys\.stderr\s*,?", "", line)
        if "from collections import *" in line:
            line = line.replace("from collections import *", "")
        if "class " not in line and any(term in line for term in io_terms):
            indentation = line[: len(line) - len(line.lstrip())]
            result.append(f"{indentation}pass")
        elif "open(" in line and "open(0" not in line:
            indentation = line[: len(line) - len(line.lstrip())]
            result.append(f"{indentation}pass")
        else:
            result.append(line)
    return "\n".join(result)


def remove_logging(source: str) -> str:
    """Remove logging, traceback, and platform-specific diagnostic calls."""
    terms = (
        "unittest.",
        "Unittest.",
        "traceback.",
        "os.write",
        "logging.",
        "os.system",
        "import division",
        "__future__",
    )
    return _replace_matching_lines(
        source,
        lambda line: "class " not in line and any(term in line for term in terms),
    )


def remove_process_creation(source: str) -> str:
    """Remove thread/process creation and replace simple thread targets by calls."""
    result: list[str] = []
    process_terms = (
        "threading.",
        "multiprocessing",
        "asyncio",
        "queue.Queue(",
        "ProcessPoolExecutor",
        "concurrent.",
        "fork(",
        "subprocess.run(",
    )
    for line in source.splitlines():
        if line.lstrip().startswith("import threading"):
            line = re.sub(r"\bimport\s+threading\s*,\s*", "import ", line)
            line = re.sub(r"\bimport\s+threading\b", "", line)
            if not line.strip():
                continue
        target = re.search(r"threading\.Thread\s*\(\s*target\s*=\s*([A-Za-z_]\w*)", line)
        if target:
            indentation = line[: len(line) - len(line.lstrip())]
            result.append(f"{indentation}{target.group(1)}()")
        elif any(term in line for term in (".start()", ".join()")):
            indentation = line[: len(line) - len(line.lstrip())]
            result.append(f"{indentation}pass")
        elif any(term in line for term in process_terms):
            indentation = line[: len(line) - len(line.lstrip())]
            result.append(f"{indentation}pass")
        else:
            result.append(line)
    return "\n".join(result)


def replace_odd_io(source: str) -> str:
    """Remove additional stream-wrapper and recursion-limit statements."""
    terms = (
        "IOWrapper",
        "FastIO",
        "StringIO(",
        "BytesIO(",
        "FastStdout",
        "IOBase",
        "setrecursionlimit(",
    )
    return _replace_matching_lines(
        source,
        lambda line: "class " not in line and any(term in line for term in terms),
    )


def remove_exit_calls(source: str) -> str:
    """Replace generated process-exit calls with syntax-safe no-ops."""
    return _replace_matching_lines(source, lambda line: "exit(" in line or "quit(" in line)


def remove_exec_calls(source: str) -> str:
    """Remove dynamic execution statements from generated programs."""
    return _replace_matching_lines(source, lambda line: "exec(" in line)


def apply_apps_compatibility(source: str) -> str:
    """Apply the small compatibility fix used by the APPS evaluator."""
    result = source.replace(".decode())", "))")
    result = "\n".join(line for line in result.splitlines() if not line.lstrip().startswith("global "))
    return result


def join_implicit_lines(source: str) -> str:
    """Join physical lines represented as non-terminating Python token lines."""
    try:
        lines = source.replace("\r\n", "\n").replace("\r", "\n").split("\n")
        tokens = list(tokenize.generate_tokens(io.StringIO(source).readline))
        merge_rows = sorted(
            {
                token.start[0] - 1
                for token in tokens
                if token.type == tokenize.NL
            },
            reverse=True,
        )
        for row in merge_rows:
            if row < 0 or row + 1 >= len(lines):
                continue
            left = lines[row].rstrip()
            right = lines[row + 1].lstrip()
            if not left or not right or left.startswith("#") or right.startswith("#"):
                continue
            if left.endswith("\\"):
                left = left[:-1].rstrip()
            lines[row : row + 2] = [f"{left} {right}"]
        for row in range(len(lines) - 2, -1, -1):
            left = lines[row].rstrip()
            right = lines[row + 1].lstrip()
            if left.endswith("\\") and right:
                lines[row : row + 2] = [f"{left[:-1].rstrip()} {right}"]
        return "\n".join(lines).strip()
    except (IndentationError, tokenize.TokenError):
        return source.strip()


def simple_sanitize_python(raw_code: object) -> str:
    """Run the lightweight, structure-preserving Python sanitization pass."""
    source = _extract_code(raw_code)
    if not source or source == "pass":
        return "pass"
    source = remove_recursion_limits(source)
    source = remove_main_guard(source)
    source = replace_identity_operators(source)
    source = apply_safe_io_replacements(source)
    source = join_implicit_lines(source)
    return remove_blank_lines(source)


def sanitize_and_strip_comments_python(raw_code: object) -> str:
    """Normalize Python syntax and remove comments and docstrings."""
    source = _extract_code(raw_code)
    if not source or source == "pass":
        return "pass"
    source = fix_ast_replacements(source)
    source = remove_recursion_limits(source)
    source = remove_main_guard(source)
    source = normalize_ast(source, remove_docstrings=True)
    source = remove_comments_and_docstrings(source, lang="python")
    source = replace_identity_operators(source)
    source = apply_safe_io_replacements(source)
    source = join_implicit_lines(source)
    return remove_blank_lines(source)


def repeated_sanitize_python(raw_code: object) -> str:
    """Run the aggressive compatibility pass used for repeated-generation data."""
    source = sanitize_and_strip_comments_python(raw_code)
    if source == "pass":
        return source
    source = replace_odd_words(source)
    source = remove_logging(source)
    source = remove_process_creation(source)
    source = replace_odd_io(source)
    source = remove_exit_calls(source)
    source = remove_exec_calls(source)
    source = apply_apps_compatibility(source)
    source = join_implicit_lines(source)
    return remove_blank_lines(source)


def sanitize_Python_function(rawcode: object) -> str:
    """Compatibility name for the lightweight Python sanitizer."""
    return simple_sanitize_python(rawcode)


def sanitize_and_strip_comments_Python_function(rawcode: object) -> str:
    """Compatibility name for comment-removing Python sanitization."""
    return sanitize_and_strip_comments_python(rawcode)


def repeated_sanitize_Python_function(rawcode: object) -> str:
    """Compatibility name for the repeated-generation sanitizer."""
    return repeated_sanitize_python(rawcode)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-path", type=Path, required=True, help="UTF-8 source file")
    parser.add_argument("--output-path", type=Path, help="Optional output file")
    parser.add_argument(
        "--mode",
        choices=("simple", "comments", "aggressive"),
        default="comments",
        help="Sanitization level",
    )
    return parser.parse_args()


def main() -> None:
    args = _parse_args()
    source = args.input_path.read_text(encoding="utf-8")
    sanitizer = {
        "simple": simple_sanitize_python,
        "comments": sanitize_and_strip_comments_python,
        "aggressive": repeated_sanitize_python,
    }[args.mode]
    result = sanitizer(source)
    if args.output_path:
        args.output_path.write_text(result + "\n", encoding="utf-8")
    else:
        print(result)


if __name__ == "__main__":
    main()
